language: python
python:
  - 2.7
  - 3.2
  - 3.5

services:
  - docker

install:
  - docker build -t jenkins-docker-setup .
  - docker run -d -p 127.0.0.1:8080:8080 -p 127.0.0.1:50000:50000 --name jenkins jenkins-docker-setup

script:
  - docker ps | grep -q jenkins
