language: python
python:
  - 2.7
  - 3.2
  - 3.5

services:
  - docker

install:
  - docker build -t sonarqube-sonartsplugin .
  - docker run -d -p 127.0.0.1:29000:9000 -p 127.0.0.1:29092:9092 --name sonar sonarqube-sonartsplugin

script:
  - docker ps | grep -q sonar
